Import('env', 'arch', 'common', 'messaging')

if arch != "Darwin":
  pandad_env = env.Clone()

  # comma-deps-libusb is a tools extra, and a device installs no python
  # dependencies at build time, so fall back to the system libusb the way
  # pandad did before the USB transport was removed.
  try:
    import libusb
    pandad_env['CPPPATH'] += [libusb.INCLUDE_DIR]
    pandad_env['LIBPATH'] += [libusb.LIB_DIR]
  except ImportError:
    pass

  libs = [common, messaging, 'pthread', 'usb-1.0']
  panda = pandad_env.Library('panda', ['panda.cc', 'spi.cc', 'usb.cc'])

  pandad_env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    pandad_env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
